---
- name: Add Nvidia PPA
  apt_repository:
    repo: "ppa:graphics-drivers/ppa"
  become: yes

- name: Update caches after PPA being added
  apt: update_cache=yes
  become: yes

- name: Install Nvidia drivers
  apt: 
    name: nvidia-driver-396
    state: latest
  become: yes
