---
- name: Symlink VSCode user settings
  file:
    src: "{{ dotfiles_repo_local_destination }}.vscode.json"
    dest: "/home/{{ ansible_ssh_user }}/.config/Code/User/settings.json"
    state: link
    force: yes